# Generated by Django 2.0.2 on 2018-02-11 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_and_W_rel',
            fields=[
                ('answer', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('kelime', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='A_quality',
            fields=[
                ('answer', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('quality', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Q_A_and_W_rel',
            fields=[
                ('question', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('answer', models.PositiveIntegerField()),
                ('kelime', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Q_and_A_compatibility',
            fields=[
                ('question', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('answer', models.PositiveIntegerField()),
                ('compatibility', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Q_and_W_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Q_quality',
            fields=[
                ('question', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('quality', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'word',
                'verbose_name_plural': 'words',
            },
        ),
        migrations.AddField(
            model_name='q_and_w_rel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordapi.Question'),
        ),
    ]
