# Generated by Django 2.0.2 on 2018-02-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'word', 'verbose_name_plural': 'words'},
        ),
    ]
