# Generated by Django 2.0.2 on 2018-02-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordapi', '0003_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_and_W_rel',
            fields=[
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wordapi.Answer')),
                ('kelime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wordapi.Word')),
            ],
        ),
        migrations.CreateModel(
            name='A_quality',
            fields=[
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wordapi.Answer')),
                ('quality', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Q_A_and_W_rel',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wordapi.Question')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wordapi.Answer')),
                ('kelime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wordapi.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Q_and_A_compatibility',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wordapi.Question')),
                ('compatibility', models.BooleanField()),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wordapi.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Q_and_W_rel',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wordapi.Question')),
                ('kelime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wordapi.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Q_quality',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wordapi.Question')),
                ('quality', models.BooleanField()),
            ],
        ),
    ]
